name = "AlphaCertified"
uuid = "899ffb7a-1330-11e9-31f4-a3063e80b191"
authors = ["Sascha Timme <sascha.timme@gmail.com>"]
version = "0.1.0"

[deps]
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
